### ISSUE TITLE
Cross Walk In (xwi) Report

### ISSUE THREAD

**Issue by Goondrious** [EQWorks/react-maps#5]
- **NOTE:** effectively same metrics as vwi/wi (https://github.com/EQWorks/react-maps/issues/4), except each row is 2 points instead of 1
- **description:** show data on people who have been seen at two locations
- **data:**
    - `[{ source_lat, source_lon, target_lat, target_lon, ...poiDetails, metrics }]`
    - [https://api.locus.place/prod/report/xwi?report_id=1556&layer_id=1428&date_type=2&start_date=2019-11-25T00:00:00.000Z&end_date=2019-11-30T00:00:00.000Z](https://api.locus.place/prod/report/xwi?report_id=1556&layer_id=1428&date_type=2&start_date=2019-11-25T00:00:00.000Z&end_date=2019-11-30T00:00:00.000Z)
- **map layers:** point, icon, arc

**Comment by geoerika** [comment]
LocusMap - done
